### ISSUE TITLE
Tab-bar-mode tabs are concealed by margins unless ridiculously high tab-bar-width values are chosen

### ISSUE THREAD

**Issue by hapst3r** [protesilaos/spacious-padding#3] opened 2024-01-13 11:09 UTC
Hej @protesilaos

I am trying to put spacious padding to use because I find it gorgeous and cleverly simple. However, I run into the problem that whenever I activate `spacious-padding-mode`, a good chunk of my tab-bar-mode tabs is concealed up to the point that I cant decipher the writing anymore.

Whereas in your 2023-11-15 presentation blog post, `spacious-padding-mode` and `tab-bar-mode` go along nicely, I run into this problem both with `emacs -Q` and with my full configuration.

### emacs -Q
![20240113T115500--emacs-q-spacious-padding](https://github.com/protesilaos/spacious-padding/assets/55704994/acf505ae-a9c0-4dd9-a101-3c8c5b8ef696)

### full configuration
![20240113T115500--full-config-spacious-padding](https://github.com/protesilaos/spacious-padding/assets/55704994/a96fcbc7-b94d-4bad-956a-79391f0c9131)

I am on openSUSE Tumbleweed GNOME, with all parts up-to-date (OS, emacs, spacious-padding).

I fear that this bug is kind of specific to GNOME, because when I change to IceWM (which is bundled with GNOME on openSUSE), I don't run into this problem.

Is anyone able to reproduce this issue with a window manager other than GNOME? Because otherwise, I suppose I'd have to report to GNOME, right?

Have a good day!

**EDIT:** It seems like GNOME Xorg does not have this problem, unlike GNOME Wayland I am using under normal circumstances. Well well, things get more specific, dont they :D

**Comment by protesilaos** [comment] 2024-01-13 12:22
Hello @hapst3r!

I cannot reproduce this on GNOME Wayland. Here is what I get:

![Screenshot from 2024-01-13 14-21-01](https://github.com/protesilaos/spacious-padding/assets/12828033/68882e3c-cbf4-45cc-95f1-28393005a5ef)

![Screenshot from 2024-01-13 14-21-09](https://github.com/protesilaos/spacious-padding/assets/12828033/270498a9-dddc-4c6d-8337-5851741e6add)

This problem was also reported on my mailing list, but SourceHut is down...

**Comment by hapst3r** [comment] 2024-01-28 08:22
Has the report on the mailing list borne fruit by any change?

**Comment by protesilaos** [comment] 2024-01-28 08:26
> From: hapst3r ***@***.***>
> Date: Sun, 28 Jan 2024 00:22:34 -0800
>
> Has the report on the mailing list borne fruit by any change?

It seems that the PGTK feature is involved. Are you using it?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by hapst3r** [comment] 2024-01-28 15:29
I am sorry, but I don't know how to properly check that. I tried searching some of the files over at the [openSUSE OBS package repository](https://build.opensuse.org/package/show/openSUSE%3AFactory/emacs), but IMO that is not very conclusive. I tried searching my filesystem for a file named `pgtk` within a `lisp/` directory (which is what is mentioned in the emacs.spec file, but `fd` couldn't locate such a file.

Is there an easy way to find it out via `emacs`? A quick web search didn't help me find something.

**Comment by protesilaos** [comment] 2024-01-29 05:37
> From: hapst3r ***@***.***>
> Date: Sun, 28 Jan 2024 07:29:58 -0800
>
> I am sorry, but I don't know how to properly check that. I tried
> searching some of the files over at the [openSUSE OBS package
> repository](https://build.opensuse.org/package/show/openSUSE%3AFactory/emacs),
> but IMO that is not very conclusive. I tried searching my filesystem
> for a file named `pgtk` within a `lisp/` directory (which is what is
> mentioned in the emacs.spec file, but `fd` couldn't locate such a
> file.
>
> Is there an easy way to find it out via `emacs`? A quick web search
> didn't help me find something.

Check the value of 'system-configuration-options'. You are searching for
the "--with-pgtk" flag.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by hapst3r** [comment] 2024-01-29 05:53
> From: hapst3r ***@***.***> Date: Sun, 28 Jan 2024 07:29:58 -0800 I am sorry, but I don't know how to properly check that. I tried searching some of the files over at the [openSUSE OBS package repository](https://build.opensuse.org/package/show/openSUSE%3AFactory/emacs), but IMO that is not very conclusive. I tried searching my filesystem for a file named `pgtk` within a `lisp/` directory (which is what is mentioned in the emacs.spec file, but `fd` couldn't locate such a file. Is there an easy way to find it out via `emacs`? A quick web search didn't help me find something.
> Check the value of 'system-configuration-options'. You are searching for the "--with-pgtk" flag.
> […](#)
> -- Protesilaos Stavrou https://protesilaos.com

Thank you for the hand-holding! Yes, emacs is indeed built `--with-pgtk`. I will think about a possibility to test whether not using pgtk helps, will report back.

**Comment by hapst3r** [comment] 2024-02-04 08:14
@protesilaos I was able to test a version of emacs without pgtk, and the issue went away (not even emacs -Q but my normal config). How to proceed (apart from "don't use emacs --with-pgtk")?

**Comment by protesilaos** [comment] 2024-02-08 09:32
> From: hapst3r ***@***.***>
> Date: Sun,  4 Feb 2024 00:14:16 -0800
>
> @protesilaos I was able to test a version of emacs without pgtk, and
> the issue went away (not even emacs -Q but my normal config). How to
> proceed (apart from "don't use emacs --with-pgtk")?

We can try to reduce the problem to a simple change in the relevant
faces. Then write down the steps to reproduce it with 'emacs -Q' and
send a bug to the Emacs maintainers.

Are you willing to do this? I am happy to explain the steps for you. And
you can add me in CC when you file the bug.

I am not sending the bug myself because I don't use PGTK.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment] 2024-02-22 12:33
Hello again! Have you had the chance to review this bug of
`spacious-padding-mode` with the PGTK build of Emacs? As I told you, I
am not using PGTK, so I won't report a bug upstream, but maybe it is
something you are interested in doing.

**Comment by hapst3r** [comment] 2024-02-25 09:41
Hej @protesilaos! So far I have not been able to do this, but I am quite willing to do this. I think I will need some assistance, though.

> We can try to reduce the problem to a simple change in the relevant faces. 

What do you mean by this?

> Then write down the steps to reproduce it with 'emacs -Q' and send a bug to the Emacs maintainers. 

Is this related to "reducing the problem" or an independent step?

**Comment by fabcontigiani** [comment] 2024-04-12 03:14
Hi! I'm experiencing the same issue. This is related to the `internal-border-width` value. According to [this bug report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=64822), it is already fixed on master.

**Comment by protesilaos** [comment] 2024-04-12 04:46
> From: Fabrizio Contigiani ***@***.***>
> Date: Thu, 11 Apr 2024 20:15:04 -0700
>
> Hi! I'm experiencing the same issue. This is related to the
> `internal-border-width` value. According to [this bug
> report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=64822), it is
> already fixed on master.

Good to know! Have you tried to rebuild Emacs to check if this is the case?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by fabcontigiani** [comment] 2024-04-12 17:32
I should have been more precise with my wording, I apologize.

I'm experiencing this issue while on Emacs 29.3 configured with PGTK. I haven't tried with Emacs built from master yet.

**Comment by protesilaos** [comment] 2024-04-13 06:29
> From: Fabrizio Contigiani ***@***.***>
> Date: Fri, 12 Apr 2024 10:33:10 -0700
>
> I should have been more precise with my wording, I apologize.

Oh, I see. No worries!

> I'm experiencing this issue while on Emacs 29.3 configured with PGTK. I haven't tried with Emacs built from master yet.

I guess we have no better option but to either wait for Emacs 30 to
become the new stable or for you to rebuild Emacs with another toolkit.
Currently I am using '--with-x-toolkit=gtk3', though I am on Xorg.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by fabcontigiani** [comment] 2024-04-13 16:22
I'll patiently wait for Emacs 30 to be released. Just wanted to point out that this was in fact an issue with Emacs itself and not `spacious-padding`.

PD: Thanks Prot, I enjoy using the packages that you maintain and your videos about Emacs have helped me a lot ^^

**Comment by protesilaos** [comment] 2024-04-14 10:51
> From: Fabrizio Contigiani ***@***.***>
> Date: Sat, 13 Apr 2024 09:22:27 -0700
>
> I'll patiently wait for Emacs 30 to be released. Just wanted to point
> out that this was in fact an issue with Emacs itself and not
> `spacious-padding`.

Great, thanks!

> PD: Thanks Prot, I enjoy using the packages that you maintain and your
> videos about Emacs have helped me a lot ^^

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment] 2024-04-29 04:16
Thanks again folks! I am closing this now.

**Closed by protesilaos** 2024-04-29 04:16 UTC
