### ISSUE TITLE
Weird visual glitches when using emacs server.

### ISSUE THREAD

**Issue by tusharhero** [protesilaos/spacious-padding#13] opened 2024-04-26 06:43 UTC
Hey @protesilaos, thank you for this amazing package.

Problem happens only when using emacs server and it doesn't occur when I start emacs without running a server.

# Screenshots
![image](https://github.com/protesilaos/spacious-padding/assets/54012021/390b52ef-3890-4713-948c-42b20d7a1f70)

# Specifications
- GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)
- Archlinux (I use the Guix package manager for Emacs.).
- KDE Plasma 6 Wayland.

**Comment by protesilaos** [comment] 2024-04-26 11:11
> From: tusharhero ***@***.***>
> Date: Thu, 25 Apr 2024 23:44:07 -0700
>
> Hey @protesilaos, thank you for this amazing package.

You are welcome!

> Problem happens only when using emacs server and it doesn't occur when I start emacs without running a server.
>
> # Screenshots
> ![image](https://github.com/protesilaos/spacious-padding/assets/54012021/390b52ef-3890-4713-948c-42b20d7a1f70)

So you are starting Emacs without 'server-mode'? Or is this still an emacsclient?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment] 2024-04-27 03:37
Does this issue go away if you re-enable `spacious-padding-mode`? Or is something else involved that sets the `:box` attribute of the mode line?

I notice that the box does not come directly from the theme (which looks like `modus-operandi-deuteranopia`) because the theme would/should set a colour for the box. Whereas here we only have a box without an explicit colour, so we see each block extend its own colour to the box (see the -22 and the date).

**Comment by tusharhero** [comment] 2024-04-27 03:52
It does go away if I re-enable `spacious-padding-mode`. I am not sure if something else is involved but here is my a relevant portion of my init.el

```elisp
  (setq custom-safe-themes t)
  (advice-add 'load-theme
              :before (lambda (theme &optional no-confirm no-enable)
                        (disable-theme (car custom-enabled-themes))))
```

The theme I am using is `ef-frost`.

**Comment by protesilaos** [comment] 2024-04-27 03:59
> From: tusharhero ***@***.***>
> Date: Fri, 26 Apr 2024 20:52:42 -0700
>
> It does go away if I re-enable `spacious-padding-mode`. I am not sure
> if something else is involved but here is a relevant portion of my
> init.el

Are you starting spacious-padding before or after loading the theme?
Perhaps that is the issue.

> [... 7 lines elided]

> The theme I am using is `ef-frost`.

Okay, same idea for the :box as with the modus-themes (I use the warm
night light and it distorts the colours...).

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by tusharhero** [comment] 2024-04-27 04:06
Spacious padding is enabled before I load the theme.

**Comment by protesilaos** [comment] 2024-04-27 04:08
> From: tusharhero ***@***.***>
> Date: Fri, 26 Apr 2024 21:06:34 -0700
>
> Spacious padding is enabled before I load the theme.

Try to change that order. Because now spacious-padding does not read the
colours of your theme at startup.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by tusharhero** [comment] 2024-04-27 04:22
I tried changing the order, it doesn't seem to change much.

**Comment by nuthub** [comment] 2024-04-28 11:12
In my *Messages* I see:

> Unable to load color "unspecified-bg"

I'm also using modus-operandi.

> Does this issue go away if you re-enable `spacious-padding-mode`? Or is something else involved that sets the `:box` attribute of the mode line?
> 

For me disabling and enabling spacious-padding-mode works around that issue.

**Comment by protesilaos** [comment] 2024-04-29 03:47
> From: Julian Flake ***@***.***>
> Date: Sun, 28 Apr 2024 04:12:53 -0700

> [... 7 lines elided]

>> Does this issue go away if you re-enable `spacious-padding-mode`? Or is something else involved that sets the `:box` attribute of the mode line?
>> 
>
> For me disabling and enabling spacious-padding-mode works around that issue. 

Yes, this is the expected behaviour. After a frame exists and a theme is
available, the "unspecified-bg" is no longer there. We get the correct
value.

Let me check how best to work around this.
 
-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment] 2024-04-29 03:58
I just added a change. Please let me know if this works for you.

**Comment by tusharhero** [comment] 2024-04-29 06:04
Hey @protesilaos, unfortunately your fix doesn't seem to work for me.

**Comment by tusharhero** [comment] 2024-04-29 06:06
I just noticed that creating a new frame by running `emacsclient -nc -a ''` fixes it. But it doesn't work the first time I run `emacsclient -nc -a ''`.

The first time I run `emacsclient -nc -a''`, it starts the emacs server if its not running. I think that may have something to do with.

**Comment by nuthub** [comment] 2024-04-29 06:16
Also not fixed for me. I start emacs exactly like tusharhero, but it doesn't make a difference, if I start `emacs --daemon` and `emacsclient -nc` separately instead.

**Comment by nuthub** [comment] 2024-04-29 06:19
Ah, opening a second frame then fixes glitch with both frames!

**Comment by protesilaos** [comment] 2024-04-29 06:41
I pushed another change. Can you please try again?

**Comment by nuthub** [comment] 2024-04-29 06:46
fixed with af8030e !

**Closed** 2024-04-29 06:52 UTC

**Comment by protesilaos** [comment] 2024-04-29 07:05
Very well! I am waiting for [another issue](https://github.com/protesilaos/spacious-padding/issues/11) and will then prepare the new release.

**Comment by alexispurslane** [comment] 2024-12-23 02:31
This issue still persists for me.

**Comment by protesilaos** [comment] 2024-12-23 07:11
@alexispurslane Can you please tell me more about your setup? Are you using a build of Emacs `--with-pgtk`?

**Comment by tusharhero** [comment] 2024-12-23 11:05
> @alexispurslane Can you please tell me more about your setup? Are you
> using a build of Emacs `--with-pgtk`?

could this be related to my issue as well?

--
tusharhero

**Comment by protesilaos** [comment] 2024-12-24 06:15
> From: tusharhero ***@***.***>
> Date: Mon, 23 Dec 2024 03:05:24 -0800
>
>> @alexispurslane Can you please tell me more about your setup? Are you
>> using a build of Emacs `--with-pgtk`?
>
> could this be related to my issue as well?

Probably. I will need to build Emacs PGTK to find out. The bug is not
reproducible on X.

These are my 'system-configuration-options':

  --prefix=/usr/local --with-x-toolkit=gtk3 --disable-gc-mark-trace
  --with-native-compilation=aot --without-gif --without-tiff
  --without-selinux --without-xinput2 --without-gpm
  --without-compress-install --without-xft --with-cairo --with-harfbuzz
  --with-tree-sitter=ifavailable --without-gsettings --without-gconf

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by GaryBlackbourne** [comment] 2025-05-08 07:50
Hello!
I was searching for this issue and tried
